### ISSUE TITLE
Date-range: from and not following same format options

### ISSUE THREAD

**Issue by juliomac** [rajit/bootstrap3-datepicker#10]
I have the following date-range HTML that I wrote based on examples from eternicode.

HTML:
```
 <div class="col-sm-3">
    <div class="input-daterange input-group" id="DatePickerId">
      <input type="text" class="input-sm form-control" data-provide="datepicker"  name="start" placeholder="{{_ 'Check-in'}}" id="startdate"/>
      <span class="input-group-addon">
        <span class="glyphicon glyphicon-calendar"></span>
      </span>
      <input type="text" class="input-sm form-control" data-provide="datepicker" name="end" placeholder="{{_ 'Check-out'}}" id="enddate"/>
      <span class="input-group-addon">
        <span class="glyphicon glyphicon-calendar"></span>
      </span>
    </div>
</div>
```

and JS:
```
Template.Form.events({
        'click #DatePickerId': function(e){
          e.preventDefault();
        	$('#DatePickerId').datepicker({
 	       	    format: 'DD, dd-mm-yyyy',
        	    startView: 0,
        	    todayBtn: "linked",
        	    language: "pt-BR",
        	    startDate: today(),
        	    endDate: InTwoYears()
        	 })
		},
});
```

However both "format" and "todayBtn" have been applied to only one of the date fields as shown:

![captura de tela 2015-06-12 12 19 10](https://cloud.githubusercontent.com/assets/3759295/8133264/a0919840-10fd-11e5-907a-da37397df55d.png)

What am I doing wrong?

**Comment by rajit** [comment]
I'll have a little investigation.

It may be that I need to update to the latest datepicker code, which I haven't done in a while now.

**Comment by rajit** [comment]
I don't include any of the locales with this package. Am I right in saying you copied one into your application yourself? This certainly makes sense and is no problem to do. Maybe in the future I can provide a package with all locales, but that'll increase the weight of the package.

I've hacked the Meteor todos example app to include a from/to datepicker for each todo item. You can check it out here: https://github.com/rajit/datepicker-todos-example

The issues that you have highlighted are not occurring on this project. The main difference I can think of is that I have initialised the datepickers in `.onRendered` instead of in the `click` event.

Check out the repository and see if it helps.

I'm going to go ahead and upgrade the datepicker now.

**Comment by rajit** [comment]
Looks like there haven't been any new releases of the datepicker, so I've nothing to upgrade.

**Comment by juliomac** [comment]
BIG THANKS!

I have changed to ```.onRendered``` as you suggested and it all worked fine. I wonder why... but that's for another investigation of mine for later.

Yes, I have used my own locale. Really pretty simple. I have put them here (https://github.com/juliomac/locales-for-Rajit-s-DatePicker-package-) in case you may have good use for them.

I would suggest that, for other locales, rather than pack it all in a big datepicker package, you may do what some other packagers have been doing. Add each language as separate packages following the parent package name. For Spanish that could be:

     rajit/bootstrap3-datepicker-locale-es

**Comment by rajit** [comment]
Great to hear you got it working!

Thank you for the locale idea, I'm setting it up now. I'll publish all of the locales as separate packages.

**Comment by rajit** [comment]
@juliomac I've published all of the locales now. If you'd like to use the `pt-BR` locale, for instance, just do:
```
$ meteor add rajit:bootstrap3-datepicker-pt-br
```
From your Meteor project.

**Comment by juliomac** [comment]
Hi Rajit, Just to let you know these new language packages worked wonderfully. THANKS!

**Comment by rajit** [comment]
Thank you for the feedback Júlio, that's great to hear!
