### ISSUE TITLE
set up multidate with Meteor autoform

### ISSUE THREAD

**Issue by shkomg** [rajit/bootstrap3-datepicker#11]
Hi,

may you, pls, help we to set up the use of ```multidate:true``` within autoform?

I'm constantly getting only one date saved. Here is my code:

template:
```{{> afQuickField name="notAvailableDates" buttonClasses="glyphicon glyphicon-calendar" datePickerOptions=dateOptions}}```

helper:
```dateOptions: function () {
return {multidate: true, todayBtn: "linked", todayHighlight: true}
} ```

schema:
```notAvailableDates: {
        type: String,
        optional:true,
        autoform: {
            afFieldInput: {
                type: "bootstrap-datepicker"
            }
        },
}```

what's wrong?

Thank you.

**Comment by rajit** [comment]
I think you might get better support if you ask this question on https://github.com/aldeed/meteor-autoform-bs-datepicker/ or https://github.com/aldeed/meteor-autoform.

I've hacked together your example in https://github.com/rajit/datepicker-todos-example.git on branch `multidate-help`. Check it out if you like.

From the `bootstrap3-datepicker` widget perspective, multidate is working well and populating the input field with a comma-separated list of dates. I expect the issue may either be in your implementation or in `autoform` or `autoform-bs-datepicker`, so you might better off asking on those repositories.

Cheers.

**Comment by shkomg** [comment]
Thank you, @rajit , yes something wrong with ```autoform``` or ```autoform-bs-datepicker```

**Comment by rajit** [comment]
Very handy, hopefully they'll accept it soon
