### ISSUE TITLE
incorrect setDates behavior for multidates

### ISSUE THREAD

**Issue by shkomg** [rajit/bootstrap3-datepicker#12]
Hi Rajit,

when I do so with ```multidates:true```

```$('[name=datePick]').datepicker('setDates', dates.split(','));```

I receive this incorrect result (only one date is marked by blue square):
![Imgur](http://i.imgur.com/ifXkYmq.png)

Thank you for your support!!!

**Comment by rajit** [comment]
I put a simple datepicker on branch `multidate-setdate` on
https://github.com/rajit/datepicker-todos-example.

If I run
```
$('[name=datePick]').datepicker('setDates', [new Date(), new Date()])
```

I can see that the dates get set correctly, though nothing appears visually
selected. Is that the problem you have?

In your code you are running `dates.split(',')` so I assume you're
providing a `String`. According to eternicode's documentation you should
provide `Date` objects here.

All I have done is repackaged eternicode's bootstrap-datepicker for Meteor.
They would be better positioned to help you with this. I don't know if they
intended for dates to be visually selected when you use setDates.

Best of luck.
