### ISSUE TITLE
bootstrap3-datepicker-fr -Unable to cycle through the months in the datepicker

### ISSUE THREAD

**Issue by digitalfrost** [rajit/bootstrap3-datepicker#15]
Using bootstrap3-datepicker-fr

Doing either
```
$('#datepicker-test').datepicker({
    language: 'fr'
  });
```
in the console or calling  via __Template.mytemplate.rendered=function()__

- Datepicker pops up OK.
- Month is September 2015.
- I can click to October 2015
- __I cannot__ click to December 2015
- __I cannot__ click back to September 2015

If I try to go the other way after the datepicker pops up I get stuck on August.

**Comment by digitalfrost** [comment]
I get the same issue if I get rid of the __fr__ package and try to just use bootstrap3-datepicker

**Comment by monasha-s** [comment]
I was having the same issue, I had a body tag in my layout template, which resulted in having 2 since meteor creates a body tag of its own, getting rid of one solved my issue.

**Comment by rajit** [comment]
@digitalfrost did the suggestion from @monasha-s work for you?

**Comment by rajit** [comment]
I'll close this issue for now — please raise a new issue, or re-open this one, if necessary.
