### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'dp.getUTCDate')

### ISSUE THREAD

**Issue by juliomac** [rajit/bootstrap3-datepicker#17]
I am getting this error message randomly.

I can't figure out why it happens some times and why it does't most of the other times.

It happens when I remove and then re-initiate date picker with other language like this:

    $('#DatePickerId').datepicker('remove');
    InitiateDatePicker(currentLang);

    InitiateDatePicker = function(lang){
        $('#DatePickerId').datepicker({
            format: DatePickerLangFormat(lang),
            startView: 0,
            todayBtn: "linked",
            language: lang,
            startDate: moment().format(MomentI18nFormat(lang)),
            endDate: InTwoYears(),
      });
    };

Is it an async issue? How can I make sure error never happens?

**Comment by dominicarrojado** [comment]
Yea this happens to me also. Slightly similar to the problem, I do want to know how to re initiate a datepicker range. Thanks!

**Comment by juliomac** [comment]
Hi @dominicarrojado , what I showed above has been so far the best way I found to re initiate date picker.

You first have to remove it and then initiate it back.

However, it does not seem to be very stable.

**Comment by dominicarrojado** [comment]
@juliomac Yea but it only works on a single datepicker. I'm using a datepicker 'range'. Initiating it back don't work somehow it only initiates once but when you remove it can't initiate back. Yea and you're right it does not seem to be very stable.

**Comment by juliomac** [comment]
Strange. Mine is also a datepicker 'range'. It is working "most" of the time as mentioned above.

**Comment by dominicarrojado** [comment]
@juliomac Can I see the codes to see how you do it? From initiating it first (with HTMLs). Then how you do the reinitiate?

**Comment by juliomac** [comment]
Sure! I will take out some things specifics to my use case and make it more generic.

Below is the Template:

  				<template name="i18nDatepicker">
					  <div class="form-group">
				    <div class="input-daterange input-group" id="DatePickerId">
				      <input type="text" class="input form-control" data-provide="datepicker"  id= "CheckIn" name="CheckIn" required
				      placeholder="Check-in"/>
				      <span class="input-group-addon">
				        <span class="glyphicon glyphicon-calendar"></span>
				      </span>
				      <input type="text" class="input form-control" data-provide="datepicker" id= "CheckOut" name="CheckOut" required
				      placeholder="Check-out"/>
				      <span class="input-group-addon">
				        <span class="glyphicon glyphicon-calendar"></span>
				      </span>
				    </div>
				  </div>
				 </template>


This the function to Initiate Datepicker:

    InitiateDatePicker = function(lang){
        $('#DatePickerId').datepicker({
            format: someFunction(lang),
            startView: 0,
            todayBtn: "linked",
            language: lang
      });
    };


Then I first initiate it:

    InitiateDatePicker(currentLang);

When I need to change the language I first remove it:

    $('#DatePickerId').datepicker('remove');

And initiate again

    InitiateDatePicker(newtLang);

Hope it helps you!

**Comment by rajit** [comment]
Hey @juliomac.

I would guess that this is from the original datepicker plugin, and not related to my Meteor packaging of it.

I've just updated rajit:bootstrap3-datepicker to v1.5.0, the latest version of eternicode's datepicker. This may help, but if it doesn't and you aren't able to get help from eternicode would you be able to recreate your issue with a repository and share it with me?

**Comment by rajit** [comment]
I'll close this due to inactivity since the last message. You can re-open it if you feel it's still an issue.
