### ISSUE TITLE
Datepicker defaultDate option 

### ISSUE THREAD

**Issue by dominicarrojado** [rajit/bootstrap3-datepicker#18]
Hope there's a defaultDate set in the option parameters, its for setting the initial/default date. Or is there another way to do this?

**Comment by juliomac** [comment]
You can use ```startDate: new Date("whatever date you want")``` for instance.

**Comment by dominicarrojado** [comment]
@juliomac really? Haven't found that on the docs. Ok will try it.

**Comment by juliomac** [comment]
A good documentation reference you can find on https://github.com/eternicode/bootstrap-datepicker .

I guess Rajit's was based on it.

**Comment by rajit** [comment]
Thanks for your help @juliomac!

I've added a basic README.md making it clearer to look at the eternicode documentation.
