### ISSUE TITLE
Event onChange Fires 3 Times

### ISSUE THREAD

**Issue by maximebodereau** [rajit/bootstrap3-datepicker#19]
Hi,

I hav a bug, my change date event fires 3 times. I look on google, and apparently, this bug was fixed.
Could you update your package/bootstrap.js core ?

Creatively, maxime

**Comment by maximebodereau** [comment]
https://github.com/eternicode/bootstrap-datepicker/pull/1337

**Comment by rajit** [comment]
Hey Maxime, thanks for the input. I've just updated core and all locales to v1.5.0.

**Comment by maximebodereau** [comment]
Perfect! Thanks!
