### ISSUE TITLE
Date picker-fa numbers are not translated 

### ISSUE THREAD

**Issue by tomvolek** [rajit/bootstrap3-datepicker#20]
HI Rajiv : 
   I am using the Persian translation :  I do see days of the week listed in farsi, but not the day numbers. 
I looked at the local file for farsi . and it is missing numbers. I have listed their translation bellow.  How can we add these to the local file ?   Thanks 

Template.form_enter_product.rendered=function() {
        $('#created-datepicker').datepicker({language: 'fa' } );
    };

0 = ۰
1 = ۱
2 = ۲
3 = ۳
4 = ۴
5 = ۵
6 = ۶
7 = ۷
8 = ۸
9 = ۹
10 = ۱۰
11 = ۱۱
12 = ۱۲
13 = ۱۳
14 = ۱۴
15 = ۱۵
16 = ۱۶
17 = ۱۷
18 = ۱۸
19 = ۱۹
20 = ۲۰
21 = ۲۱
22 = ۲۲
23 = ۲۳
24 = ۲۴
25 = ۲۵
26 = ۲۶
27 = ۲۷
28 = ۲۸
29 = ۲۹
30 = ۳۰
31 = ۳۱

**Comment by rajit** [comment]
Sorry for the delay.

If you ask the eternicode guys (https://github.com/eternicode/bootstrap-datepicker) to add Persian numbers to their Persian translation, I'll update to their latest code and you'll get it in this Meteor package.

I'll close this issue, but please open a new one when you want me to update to the latest code.

**Comment by tomvolek** [comment]
Thanks Rajit, I posted an issue on the : 
Please to : https://github.com/eternicode/bootstrap-datepicker/issues/1736
Hope they answer or fix it soon.  will keep you posted... 
Thanks again
