### ISSUE TITLE
'change' event leads to maximum call stack size exception (update request)

### ISSUE THREAD

**Issue by drobbins** [rajit/bootstrap3-datepicker#22]
Hi, thanks for maintaining this wrapper! I've run into a bug that was fixed in 1.5.1 upstream (https://github.com/eternicode/bootstrap-datepicker/issues/1628). Any chance we could get an update?

**Comment by drobbins** [comment]
Later testing also confirms that downgrading to `rajit:bootstrap3-datepicker@1.4.1` also works for this particular bug.

**Comment by rajit** [comment]
Thanks for the prompt, I'll update!

**Comment by rajit** [comment]
v1.5.1 published
