### ISSUE TITLE
Finnish locale version 1.5.1 broken

### ISSUE THREAD

**Issue by hazio** [rajit/bootstrap3-datepicker#23]
Hello!
bootstrap-datepicker.fi.min.js file is not updated to 1.5.1 version. It should be repacked.

**Comment by rajit** [comment]
I actually can't see any changes in the Finnish locale in the [eternicode/bootstrap-datepicker](https://github.com/eternicode/bootstrap-datepicker) project.

Am I missing something? I'm using tag v1.5.1 from their project.

If I am, please re-open this issue and let me know.
