### ISSUE TITLE
Does not trigger react's valuelink function on change

### ISSUE THREAD

**Issue by parshwa** [rajit/bootstrap3-datepicker#24]
I am using your package with react. Here is the code:
`<input type="text" valueLink={this.dateValueLink('date-0')} className="form-control tripDatePicker" placeholder="Select Date"/>`

I am initiating datepicker in componentDidMount
`componentDidMount: function () {
    $('.tripDatePicker').datepicker({
        startDate: "today",
        autoclose: true,
        format: "dd/mm/yyyy"
    });
  },`

Datepicker comes properly and when I select a date, it shows up in input field. But my valuelink's requestChange function does not fire.
I know there is option of using event like .on('changeDate'), but it will make things very difficult for me.

Is there anyway by which I can use valuelink with this datepicker?

**Comment by rajit** [comment]
Hey @parshwa, I haven't used this with react yet. You may find more help if you ask your question on https://github.com/eternicode/bootstrap-datepicker (FYI: this project is just a simple Meteor wrapping of that project)

If you don't get a good answer there, come back here and re-open the issue. It'd help me if you could setup an example project with React demonstrating the issue in that case.

Best of luck!

**Comment by parshwa** [comment]
Hi @rajit,

Thanks. I am using it with Meteor and react. 
I will ask in eternicode/bootstrap-datepicker.

Thank you!
