### ISSUE TITLE
Month, Year Switch causes datepicker to freeze 

### ISSUE THREAD

**Issue by mario589736** [rajit/bootstrap3-datepicker#26]
I have it also in Stackoverflow:
[Month, Year Switch causes datepicker to freeze](http://stackoverflow.com/questions/36545350/meteor-aldeedautoform-bs-datepicker-month-year-switch-causes-datepicker-to-fr)

Any Ideas? Thanks!

**Comment by MateuLlull** [comment]
+1

**Comment by MateuLlull** [comment]
I realize that if you change the month, the plugin adds a new `<div class="datepicker ...</div>` to the HTML. 

This is an issue of the plugin. Maybe @eternicode can check it.

**Comment by MateuLlull** [comment]
Finally I found the solution. Meteor adds more than only one `<body>` and the plugin doesn't check if there is more than one `<body>`, and of course this breaks the funtionality of the plugin. 

I solved it with this code:
```
$('.datepicker').datepicker({
     container: 'html'
});
```

Regards!

**Comment by rajit** [comment]
Sorry for the delay @mario589736.

Did what @MateuLlull say help you at all? I'm not able to reproduce this with any simple integration. @mario589736 could you prepare a basic repository that reproduces the issue? I'd be happy to debug it.
