### ISSUE TITLE
bootstrap4

### ISSUE THREAD

**Issue by nick-preda** [rajit/bootstrap3-datepicker#30]
is it also made for bootstrap 4?

i tried implementing it inside, but nothing happens.
are there some tweaks to be done?

thanks

**Comment by rajit** [comment]
Hi @nick-preda, this package is based on https://github.com/uxsolutions/bootstrap-datepicker so whatever Bootstrap version they support is what version this supports.

This issue on their repository indicates how you might be able to adapt your project to work with Bootstrap 4: https://github.com/uxsolutions/bootstrap-datepicker/issues/2343.

Sorry for such a large delay in responding!
