### ISSUE TITLE
Add GitHub repo URL, e.g. Atmosphere

### ISSUE THREAD

**Issue by dandv** [rajit/bootstrap3-datepicker#7]
Example:

[![Adding GitHub repo URL](https://cloud.githubusercontent.com/assets/33569/6536430/76a7d88e-c402-11e4-8883-6ab2c7b8c30a.png)](https://github.com/dandv/meteor-webix)

**Comment by rajit** [comment]
I'm a bit confused what the request is here.

The title says "Add GitHub repo URL" and then says "e.g. Atmosphere". And then the screenshot shows the _Atmosphere_ URL being added to the description on the GitHub repo.

Are you suggesting I link to Atmosphere from the GitHub description?

**Comment by rajit** [comment]
I can see the benefit of adding the Atmosphere URL, so I've gone ahead and done that. Please re-open this if you actually meant something else.

**Comment by dandv** [comment]
Perfect, thanks!
