### ISSUE TITLE
Localization?

### ISSUE THREAD

**Issue by juliomac** [rajit/bootstrap3-datepicker#8]
Can't make it work. Does this package comes with any language other than "en"?

How to add it on Meteor? Tried the $.fn.datepicker.dates['en'] suggested at eternicode/bootstrap-datepicker i18n doc page, but the app crashes. 

Any ideas?

**Comment by juliomac** [comment]
Solved my own problem...

Just added the function in the at the beginning of the same js file with the Template Helpers.

**Comment by rajit** [comment]
Glad to hear you've figured it out!

**Comment by Roshdy** [comment]
@juliomac You can add it globally in a Meteor.startup() function
